### ISSUE TITLE
Better handling of multiple node versions

### ISSUE THREAD

**Issue by MitchLillie** [thingsSDK/thingssdk-cli#26]
Steps: 
0. Use `nvm` to manage versions
1. `nvm use 6.4`
2. `npm i -g thingssdk/thingssdk-cli`
3. `nvm use 6.6`
4. `thingssdk new foo`
5. `Error: Module version mismatch. Expected 48, got 47.`
6. OK, let's install with this node version. `npm i -g thingssdk/thingssdk-cli`
7. `thingssdk new foo`
8. `Error: Module version mismatch. Expected 48, got 47.`

Expected: 
`thingssdk` creates a new project, as expected, for whatever (minor) version of node being used.
Or README explains a lock to node 6.4.x.

Workaround: 
`nvm use 6.4`

**Comment by TrevorJTClarke** [comment]
Confirmed, using `nvm use 6.4` is stable. I was getting the error `UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: Error transforming`.

**Comment by chalkers** [comment]
I think the issues surround the native bindings. When you install a module globally and you use a different node module the compiled native modules are referencing headers for another node version.

You need to probably uninstall and re-install thingssdk-cli for every new version of node you use, when using it globally.
