### ISSUE TITLE
Option to push code without repl launching

### ISSUE THREAD

**Issue by TrevorJTClarke** [thingsSDK/thingssdk-cli#28]
I support this might be a nice feature, as I don't always need to see the repl.

**Comment by chalkers** [comment]
OK so the two deploy commands we have now are

```
npm run dev
```

Runs the script on the board but doesn't save and opens repl.

Then we have:
```
npm run deploy
```
Which saves the script on the board and doesn't start a REPL

Would you want a dev that didn't repl too?

**Comment by TrevorJTClarke** [comment]
`deploy` is probably sufficient, the purpose was to get away from always automatically starting the repl. Since I was testing things that didn't require it, it was slowing me down.
