### ISSUE TITLE
Generate a devices.json file

### ISSUE THREAD

**Issue by chalkers** [thingsSDK/thingssdk-cli#3]
When a new project is created there needs to be a prompt to...

"Insert your device. Press enter when ready..."
"Select Port: "
"[1] COM7"

"Select Buad Rate:"
[1] 115200
[2] 9600

(Maybe 115200 is default then the user can enter what they like)

Runtime should be automatic accessed from `argv.runtime`

devices.json should be in the root of the thingsSDK project generated. Should also be added to the `.gitignore`. https://github.com/thingsSDK/thingssdk-cli/issues/4

```
{
    "devices": {
        "COM7": {
            "baud_rate": 115200,
            "runtime": "espruino"
        }
    }
}
```

Would be nice to have a command called `thingssdk devices`

**Comment by samjulien** [comment]
I'll start researching/working on this one.

**Comment by samjulien** [comment]
Helpful article for reference: https://www.sitepoint.com/javascript-command-line-interface-cli-node-js/

**Comment by samjulien** [comment]
Note from Slack: CLI should use serial port to see available ports, then select 115200 for ESP based boards or 9600 for Espruino Pico boards.
