### ISSUE TITLE
Option to have dev mode, with a live-reload auto flash

### ISSUE THREAD

**Issue by TrevorJTClarke** [thingsSDK/thingssdk-cli#30]
Continuous development would be even better if code could be watched and then build directly to device. 

See this line for reference:
[Espruino Strategy Utils](https://github.com/thingsSDK/thingssdk-espruino-strategy/blob/master/utils.js#L22)

Could help development flow immensely

**Comment by chalkers** [comment]
I'm reluctant to have a watch mode - don't know how this little micro could cope. But `npm run dev` runs the repl for interactive debugging for now.

I'm going to close this for now - feel free to experiment and let me know how it the `watch` workflow feels :)

**Comment by TrevorJTClarke** [comment]
Totally understand. :) I've played with two setups so far, but not really happy with it yet. (nodemon, watcher) I think a better approach will come if there was some way to have hot module reloading or just a simpler flash mode with logging. This would allow a child process to listen for changes with a debounce of sorts, so the chip doesn't get killed from so many updates.
