### ISSUE TITLE
Any precedent for including modules?

### ISSUE THREAD

**Issue by AYapejian** [thingsSDK/thingssdk-cli#39]
Before I came up with a solution just wanted to know if anyone uses this in a way that you can require modules.  For instance, create a file, say `driver.js` require this in `main.js` and have the build compile both (probably in a single file for deploy) prior to uploading?

I have a couple of thoughts, probably something extensible like babel or webpack but don't want to waste time if I missed a way to do this or someone is already on it.

**Comment by AYapejian** [comment]
Ok, nm... I see rollup in the espruino strategy modules, I'll take a look and post there if need be

**Comment by chalkers** [comment]
Hey @AYapejian I'm currently writing a driver over here https://github.com/thingsSDK/HT16K33 you can use as a template.
