### ISSUE TITLE
Testing Strategy

### ISSUE THREAD

**Issue by ariesshrimp** [thingsSDK/thingssdk-cli#7]
Currently there's no way to meaningfully test the CLI functions. `mocha`'s installed, but there are no exports anywhere, so there's no way to require any functions in test files. We should decide on a general testing strategy so that people can include unit tests with their PR's.

A starting point might be to agree on what to export from `bin/thingssdk.js`, which is currently where all code under active development lives.

**Comment by ariesshrimp** [comment]
One idea is to just export everything from `bin/thingssdk.js` for granular testing. As a CLI tool there may not be any reason to care about what we expose, since developers won't really be importing anything from it into their scripts.

**Comment by ariesshrimp** [comment]
So this is actually a more complex issue than it seems at first given the structure of the `bin/thingssdk.js` script. For example:

``` javascript
// bin/thingssdk.js
// line 14
const argv = require("yargs")
        .version(cliPackage.version)
        .command(require("./commands/new"))
        .demand(1)
        .help()
        .argv
```

Seems to produce some side affects that makes `require`ing the files a nuisance. I'm not sure what the right way forward is. I'd guess it's either:
1. Looking into [`yargs`](https://www.npmjs.com/package/yargs) to try and conditionally set these parameters in a test environment. **Or**:
2. Breaking this script up into smaller modules that can be tested individually. For example, having `createApplication` live separately nearby, and `require`ing it in both the main script and any test scripts that need it.

**Comment by chalkers** [comment]
It looks like express generator literally "runs" the command line app in their tests - it looks like they do integration-level testing. 

https://github.com/expressjs/generator/blob/master/test/cmd.js#L569-L604

I do like the idea of exporting out many of the "core" functions in to utility methods we could test. Would require some refactoring since we have `argv` available to all functions. Thoughts @craigsdennis, @joefraley, @samjulien?

**Comment by chalkers** [comment]
From our chat @joefraley. @samjulien and @craigsdennis I think we should curry so we can test.

These are my thoughts :)

``` javascript
//new project/name --runtime=espruino --baud_rate=115200
//device add --runtime=espruino
//check --runtime=espruino

const comandLine = (command, options) => runtime => baud_rate => {

}
```

**Comment by chalkers** [comment]
Looks like using the command "module" syntax for `yargs` looks like the way to go.

Each "command" in the commands directory has a `handler` entry point which can be tested.

**Comment by chalkers** [comment]
Thanks for starting this @joefraley. I think testing the `createApplication` function is the thing that is only required I think testing each function individually could be brittle - `const createApplication = require("../../bin/commands/new.js").handler;`

**Comment by chalkers** [comment]
We should probably add coverage with instanbul or something like that too to make sure that we're getting good coverage of the code.

**Comment by ariesshrimp** [comment]
Agree.

**Comment by chalkers** [comment]
Added coverage `npm run test:coverage`

**Comment by chalkers** [comment]
"100% code coverage"
